services:
  - type: web
    name: music-band-api
    env: ruby
    plan: free
    buildCommand: ./bin/render-build.sh
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: music-api
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: NODE_ENV
        value: production
      - key: RACK_ENV
        value: production
      - key: RAILS_ENV
        value: production

  - type: web
    name: music-band-client
    env: static
    plan: free
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: music-api
    plan: free
