services:
  - type: web
    name: music-band-api
    env: ruby
    plan: free
    buildCommand: ./bin/render-build.sh
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: music-api
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RACK_ENV
        value: production
      - key: RAILS_ENV
        value: production

databases:
  - name: music-api
    plan: free
